// spooncheck config, generated by /edit.html

export const HANDLE = 'rawvampyre';
export const TWITCH = 'twitch.tv/rawvampyre';

export const VERDICTS = [
  { min: 99, name: 'OCEAN SIZED LADLE', blurb: 'did you steal a jmod account?' },
  { min: 90, name: 'GOLDEN SPOON', blurb: 'nice streamer client' },
  { min: 60, name: 'SPOON', blurb: 'blessed account' },
  { min: 40, name: 'AVERAGE', blurb: 'perfectly balanced' },
  { min: 30, name: 'GOING DRY', blurb: 'it could be worse...' },
  { min: 10, name: 'DRY', blurb: 'time to cry on reddit' },
  { min: 1, name: 'BONE DRY', blurb: 'aya has a chance to assign 15-30 of you' },
  { min: -1, name: 'STATISTICALLY CURSED', blurb: 'reported.' },
];

export const WEIGHTS = {
  'bring': 0.5,
  'tankhelm': 0.75,
  'tankbody': 0.75,
  'tanklegs': 0.75,
  'ddef': 0.5,
  'zaxe': 0.5,
  'spine': 0.5,
  'wsceptre': 0.5,
  'hallowfell': 0.75,
  'bloodset': 0.75,
  'blueset': 0.75,
  'eclipseset': 0.75,
  'deadeye': 0.5,
  'vigour': 0.5,
  'twinflame': 0.5,
  'dhwand': 0.5,
  'dpick': 0.5,
  'dwh': 2,
  'zenyte': 1.5,
  'jaw': 1,
  'synapse': 1,
  'bclaw': 1,
  'cseed': 1.25,
  'bowfa': 2.5,
  'tanz': 1.5,
  'trident': 1,
  'tent': 0.5,
  'whip': 0.75,
  'unsired': 0.5,
  'occult': 0.75,
  'icon': 0.5,
  'venator': 1.25,
  'heart': 3,
  'egem': 0.5,
  'bhilt': 0.75,
  'bcp': 1,
  'tass': 1,
  'zspear': 0.75,
  'vwgem': 2,
  'vwblade': 1.25,
  'vwhilt': 1.75,
  'prim': 1.5,
  'eternal': 1,
  'peg': 0.5,
  'claw': 1.75,
  'hleather': 1.25,
  'nox': 1.25,
  'afang': 1.5,
  'efang': 1.75,
  'kisten': 1.25,
  'fang': 1.5,
  'lightb': 0.75,
  'ward': 0.5,
  'mmask': 0.5,
  'mbody': 1.25,
  'mchaps': 1,
  'shadow': 2.75,
  'horn': 1,
  'oathhelm': 1.5,
  'oathchest': 1.5,
  'oathlegs': 1.5,
  'ayak': 1.5,
  'cloth': 1,
  'treads': 1.5,
  'ultor': 1.5,
  'magus': 1.5,
  'axehead': 1,
  'dukeeye': 1,
  'lure': 1,
  'siren': 1,
  'dex': 1.25,
  'arcane': 0.75,
  'dclaws': 1.5,
  'anchat': 1.5,
  'anctop': 2,
  'ancbot': 1.75,
  'emaul': 1.75,
  'tbow': 3,
  'avernic': 1.5,
  'scythe': 2.75,
  'inqmace': 2.5,
  'inqhelm': 1.25,
  'inqhauberk': 1.75,
  'inqskirt': 1.5,
  'nstaff': 1.5,
  'eldritch': 1,
  'volatile': 0.5,
  'harm': 2.25,
  'torvahelm': 1.5,
  'torvabody': 1.25,
  'torvalegs': 1,
  'nihil': 2.5,
  'vambs': 1.75,
};

export const SECTION_TITLES = {
  'the early game': 'EARLY',
  'varlamore era': 'VARLAMORE + TITANS',
  'the big unlocks': 'MID MISC',
  'demon business': 'DEMON TIME',
  'the gauntlet': 'CG',
  'slayer era': 'LATE MISC',
  'superiors': 'SUPERIORS',
  'god wars': 'GWD',
  'the wilderness section': 'WILDY',
  'cerberus': 'CERB',
  'hydra': 'HYDRA',
  'araxxor': 'ARAXXOR',
  'maggot king': 'MAGGOT KING',
  'yama': 'YAMA',
  'doom of mokhaiotl': 'DOOM',
  'desert treasure 2': 'DT2',
  'tombs of amascut': 'TOA',
  'chambers of xeric': 'COX',
  'theatre of blood': 'TOB',
  'phosanis nightmare': 'PNM',
  'nex': 'NEX',
};

export function sectionTitle(key) {
  return SECTION_TITLES[key] ?? key;
}

export const ORDER = {
  'the early game': ['bring', 'tankhelm', 'tankbody', 'tanklegs', 'ddef', 'zaxe', 'spine', 'wsceptre', 'hallowfell'],
  'varlamore era': ['bloodset', 'blueset', 'eclipseset', 'deadeye', 'vigour', 'twinflame', 'dhwand'],
  'the big unlocks': ['dpick', 'dwh', 'zenyte', 'jaw'],
  'demon business': ['synapse', 'bclaw'],
  'the gauntlet': ['cseed', 'bowfa'],
  'slayer era': ['tanz', 'trident', 'tent', 'whip', 'unsired', 'occult', 'icon', 'venator'],
  'superiors': ['heart', 'egem'],
  'god wars': ['bhilt', 'bcp', 'tass', 'zspear'],
  'the wilderness section': ['vwgem', 'vwblade', 'vwhilt'],
  'cerberus': ['prim', 'eternal', 'peg'],
  'hydra': ['claw', 'hleather'],
  'araxxor': ['nox', 'afang'],
  'maggot king': ['efang', 'kisten'],
  'yama': ['horn', 'oathhelm', 'oathchest', 'oathlegs'],
  'doom of mokhaiotl': ['ayak', 'cloth', 'treads'],
  'desert treasure 2': ['ultor', 'magus', 'axehead', 'dukeeye', 'lure', 'siren'],
  'tombs of amascut': ['fang', 'lightb', 'ward', 'mmask', 'mbody', 'mchaps', 'shadow'],
  'chambers of xeric': ['dex', 'arcane', 'dclaws', 'anchat', 'anctop', 'ancbot', 'emaul', 'tbow'],
  'theatre of blood': ['avernic', 'scythe'],
  'phosanis nightmare': ['inqmace', 'inqhelm', 'inqhauberk', 'inqskirt', 'nstaff', 'eldritch', 'volatile', 'harm'],
  'nex': ['torvahelm', 'torvabody', 'torvalegs', 'nihil', 'vambs'],
};

// browser-side overrides saved by /edit.html take effect on top of
// this file.
try {
  if (typeof localStorage !== 'undefined') {
    const ov = JSON.parse(localStorage.getItem('spooncheck-config-v2') ?? 'null');
    if (ov) {
      if (ov.titles) Object.assign(SECTION_TITLES, ov.titles);
      if (ov.order && Object.keys(ov.order).length) {
        for (const k of Object.keys(ORDER)) delete ORDER[k];
        Object.assign(ORDER, ov.order);
      }
      if (ov.weights) Object.assign(WEIGHTS, ov.weights);
      if (ov.verdicts?.length) {
        VERDICTS.length = 0;
        VERDICTS.push(...ov.verdicts);
      }
    }
  }
} catch {
  /* a broken override never breaks the app */
}
